export LC_ALL=C.UTF-8
export LANG=C.UTF-8

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

export LENCON2_DB_HOST=localhost
export LENCON2_DB_PORT=3306
export LENCON2_DB_USER=lencon
export LENCON2_DB_PASSWORD=lencon
export LENCON2_DB_NAME=lencon2

alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
